services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: beer-styles-api-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=beer_styles_db
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
      - ./scripts:/scripts
    depends_on:
      db:
        condition: service_healthy
    networks:
      - beer-network
    command: yarn dev

  db:
    image: postgres:latest
    container_name: beer_styles_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beer_styles_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - beer-network

networks:
  beer-network:
    driver: bridge

volumes:
  postgres_data_dev: